# Generated by Django 5.1.1 on 2024-09-21 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('Tanzania', 'Tanzania'), ('Ghana', 'Ghana')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
