# Generated by Django 5.1.1 on 2024-09-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customuser_country_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
