# Generated by Django 5.1.1 on 2024-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_farmer_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
