# Generated by Django 5.1.1 on 2024-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_farmer_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='area_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crops',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crops_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
