# Generated by Django 5.1.1 on 2024-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_farmer_area_unit_alter_farmer_crops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='cassava',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='maize',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='own_phone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='rice',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='sorghum',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='yam',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
