# Generated by Django 5.1.1 on 2024-09-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_farmer_cassava_alter_farmer_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
